

---


# Handling Missing Data with Pandas

pandas borrows all the capabilities from numpy selection + adds a number of convenient methods to handle missing values. Let's see one at a time:

In [1]:
import numpy as np
import pandas as pd

**Pandas utility functions**

Similarly to `numpy`, pandas also has a few utility functions to identify and detect null values:

In [ ]:
pd.isnull(np.nan)

True

In [ ]:
pd.isnull(None)

True

In [ ]:
pd.isna(np.nan)

True

In [ ]:
pd.isna(None)

True

The opposite ones also exist:

In [ ]:
pd.notnull(np.nan)

False

In [ ]:
pd.notnull(None)

False

In [ ]:
pd.notnull(3)

True

These functions also work with Series and ` DataFrames`:

In [ ]:
pd.Series([1,2,3,np.nan,np.nan,5])

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    5.0
dtype: float64

In [ ]:
pd.isnull(pd.Series([1,2,3,np.nan,np.nan,5]))

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [ ]:
pd.notnull(pd.Series([1,2,3,np.nan,np.nan,5]))

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [ ]:
pd.DataFrame({
    'A' : [10,11,12,13],
    'B' : [20,np.nan,22,23],
    'C' : [30,31,32,np.nan],
    'D' : [40,np.nan,42,43]
}, index=['R1','R2','R3','R4'])

     A     B     C     D
R1  10  20.0  30.0  40.0
R2  11   NaN  31.0   NaN
R3  12  22.0  32.0  42.0
R4  13  23.0   NaN  43.0

In [ ]:
pd.isnull(pd.DataFrame({
    'A' : [10,11,12,13],
    'B' : [20,np.nan,22,23],
    'C' : [30,31,32,np.nan],
    'D' : [40,np.nan,42,43]
}, index=['R1','R2','R3','R4']))

        A      B      C      D
R1  False  False  False  False
R2  False   True  False   True
R3  False  False  False  False
R4  False  False   True  False

In [ ]:
pd.notnull(pd.DataFrame({
    'A' : [10,11,12,13],
    'B' : [20,np.nan,22,23],
    'C' : [30,31,32,np.nan],
    'D' : [40,np.nan,42,43]
}, index=['R1','R2','R3','R4']))

       A      B      C      D
R1  True   True   True   True
R2  True  False   True  False
R3  True   True   True   True
R4  True   True  False   True



---

# Pandas Operations with Missing Values
Pandas manages missing values more gracefully than numpy. nans will no longer behave as "viruses", and operations will just ignore them completely:

In [ ]:
pd.Series([1,2,3,np.nan]).count()

np.int64(3)

In [ ]:
pd.Series([1,2,3,np.nan]).sum()

np.float64(6.0)

In [ ]:
pd.Series([3,3,np.nan]).mean()

np.float64(3.0)

# Filtering missing data
As we saw with `numpy`, we could combine boolean selection + `pd.isnull` to filter out those nans and null values:

In [3]:
s = pd.Series([1,2,np.nan,np.nan,4])
s

0    1.0
1    2.0
2    NaN
3    NaN
4    4.0
dtype: float64

In [ ]:
pd.notnull(s)

0     True
1     True
2    False
3    False
4     True
dtype: bool

In [ ]:
pd.isnull(s)

0    False
1    False
2     True
3     True
4    False
dtype: bool

In [ ]:
pd.notnull(s).sum()

np.int64(3)

In [ ]:
pd.isnull(s).sum()      # Can also write as pd.isna(s)

np.int64(2)

In [ ]:
s[pd.notnull(s)]

0    1.0
1    2.0
4    4.0
dtype: float64

But both `notnull` and `isnull` are also methods of `Series` and `DataFrames`, so we could use it that way:

In [4]:
s

0    1.0
1    2.0
2    NaN
3    NaN
4    4.0
dtype: float64

In [ ]:
s.isnull()

0    False
1    False
2     True
3     True
4    False
dtype: bool

In [ ]:
s.notnull()

0     True
1     True
2    False
3    False
4     True
dtype: bool

In [ ]:
s[s.notna()]

0    1.0
1    2.0
4    4.0
dtype: float64

---
# Dropping null values
Boolean selection + `notnull()` seems a little bit verbose and repetitive. And as we said before: any repetitive task will probably have a better, more DRY way. In this case, we can use the `dropna` method:

In [ ]:
s

0    1.0
1    2.0
2    NaN
3    NaN
4    4.0
dtype: float64

In [ ]:
s.dropna()

0    1.0
1    2.0
4    4.0
dtype: float64

---
# Dropping null values on DataFrames
You saw how simple it is to drop `na`s with a `Series`. But with `DataFrames`, there will be a few more things to consider, because you can't drop single values. You can only drop entire columns or rows. Let's start with a sample `DataFrame`:

In [18]:
df = pd.DataFrame({
    'C1' : [1,2,np.nan,3],
    'C2' : [4,5,np.nan,np.nan],
    'C3' : [np.nan,4,np.nan,8],
    'C4' : [12,13,14,15]
})
df

    C1   C2   C3  C4
0  1.0  4.0  NaN  12
1  2.0  5.0  4.0  13
2  NaN  NaN  NaN  14
3  3.0  NaN  8.0  15

In [ ]:
df.shape

(4, 4)

In [ ]:
df.size

16

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      3 non-null      float64
 1   C2      2 non-null      float64
 2   C3      2 non-null      float64
 3   C4      4 non-null      int64
dtypes: float64(3), int64(1)
memory usage: 260.0 bytes

In [ ]:
df.isnull()

      C1     C2     C3     C4
0  False  False   True  False
1  False  False  False  False
2   True   True   True  False
3  False   True  False  False

In [ ]:
df.isnull().sum()                              # Remember: It always checks the value column wise

C1    1
C2    2
C3    2
C4    0
dtype: int64

In [ ]:
df.notnull().sum()

C1    3
C2    2
C3    2
C4    4
dtype: int64

The default `dropna` behavior will drop all the rows in which any null value is present:

In [ ]:
df

    C1   C2   C3  C4
0  1.0  4.0  NaN  12
1  2.0  5.0  4.0  13
2  NaN  NaN  NaN  14
3  3.0  NaN  8.0  15

In [ ]:
df.dropna()                                # Here Row 1 is ot deleted since it does not contain any null values

    C1   C2   C3  C4
1  2.0  5.0  4.0  13

In this case we're dropping rows. Rows containing null values are dropped from the DF. You can also use the axis parameter to drop columns containing null values:

In [ ]:
df.dropna(axis=1)              # axis='columns' also works

   C4
0  12
1  13
2  14
3  15

In this case, any row or column that contains **at least** one null value will be dropped. Which can be, depending on the case, too extreme. You can control this behavior with the how parameter. Can be either `'any'` or `'all'`:

In [ ]:
df2 = pd.DataFrame({
    'Column A': [1, np.nan, 30],
    'Column B': [2, np.nan, 31],
    'Column C': [np.nan, np.nan, 100]
})
df2

   Column A  Column B  Column C
0       1.0       2.0       NaN
1       NaN       NaN       NaN
2      30.0      31.0     100.0

In [ ]:
df2.dropna(how='all')

   Column A  Column B  Column C
0       1.0       2.0       NaN
2      30.0      31.0     100.0

In [ ]:
df2.dropna(how='any')             # default behaviour

   Column A  Column B  Column C
2      30.0      31.0     100.0

You can also use the `thresh` parameter to indicate a threshold (a minimum number) of non-null values for the row/column to be kept:

In [ ]:
df

    C1   C2   C3  C4
0  1.0  4.0  NaN  12
1  2.0  5.0  4.0  13
2  NaN  NaN  NaN  14
3  3.0  NaN  8.0  15

In [ ]:
df.dropna(thresh=3)                            # Or df.dropna(thresh= 3, axis=0)

    C1   C2   C3  C4
0  1.0  4.0  NaN  12
1  2.0  5.0  4.0  13
3  3.0  NaN  8.0  15

In [ ]:
df.dropna(thresh=3,axis='columns')

    C1  C4
0  1.0  12
1  2.0  13
2  NaN  14
3  3.0  15



---

# Filling null values
Sometimes instead than dropping the `null` values, we might need to replace them with some other value. This highly depends on your context and the dataset you're currently working. Sometimes a `nan` can be replaced with a `0`, sometimes it can be replaced with the `mean` of the sample, and some other times you can take the closest value. Again, it depends on the context. We'll show you the different methods and mechanisms and you can then apply them to your own problem.

In [5]:
s

0    1.0
1    2.0
2    NaN
3    NaN
4    4.0
dtype: float64

In [7]:
s.fillna(0)          # It fills the Na values with 0

0    1.0
1    2.0
2    1.0
3    1.0
4    4.0
dtype: float64

In [8]:
s.fillna(s.mean())

0    1.000000
1    2.000000
2    2.333333
3    2.333333
4    4.000000
dtype: float64

**Filling nulls with contiguous (close) values**

The `method` argument is used to fill null values with other values close to that null one:

In [9]:
s.fillna(method='ffill')                                          # method='ffill' stands for "forward fill".

<ipython-input-9-1b2d630da9dd>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.fillna(method='ffill')

0    1.0
1    2.0
2    2.0
3    2.0
4    4.0
dtype: float64

In [10]:
s.fillna(method='bfill')                                  # method='bfill' means "backward fill"

<ipython-input-10-3624d7f4ebdb>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.fillna(method='bfill')

0    1.0
1    2.0
2    4.0
3    4.0
4    4.0
dtype: float64


This can still leave null values at the extremes of the Series/DataFrame:

In [16]:
pd.Series([np.nan, 3, np.nan, 9]).fillna(method='ffill')

<ipython-input-16-80c03cda8078>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  pd.Series([np.nan, 3, np.nan, 9]).fillna(method='ffill')

0    NaN
1    3.0
2    3.0
3    9.0
dtype: float64

In [17]:
pd.Series([np.nan,3,np.nan,9]).fillna(method='bfill')

<ipython-input-17-f68710a1d7a1>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  pd.Series([np.nan,3,np.nan,9]).fillna(method='bfill')

0    3.0
1    3.0
2    9.0
3    9.0
dtype: float64

**Filling null values on DataFrames**

The `fillna method` also works on `DataFrames`, and it works similarly. The main differences are that you can specify the `axis` (as usual, rows or columns) to use to fill the values (specially for methods) and that you have more control on the values passed:

In [19]:
df

    C1   C2   C3  C4
0  1.0  4.0  NaN  12
1  2.0  5.0  4.0  13
2  NaN  NaN  NaN  14
3  3.0  NaN  8.0  15

In [21]:
# df.fillna({'Column A': 0, 'Column B': 99, 'Column C': df['Column C'].mean()})

df.fillna({
    'C1': 0,
    'C2': 99,
    'C3':df['C3'].mean()
})

    C1    C2   C3  C4
0  1.0   4.0  6.0  12
1  2.0   5.0  4.0  13
2  0.0  99.0  6.0  14
3  3.0  99.0  8.0  15

In [23]:
df.fillna(method='ffill',axis = 0)

<ipython-input-23-37d84c0d4d86>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',axis = 0)

    C1   C2   C3  C4
0  1.0  4.0  NaN  12
1  2.0  5.0  4.0  13
2  2.0  5.0  4.0  14
3  3.0  5.0  8.0  15

In [24]:
df.fillna(method='ffill',axis=1)

<ipython-input-24-ab3954fbfbe2>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',axis=1)

    C1   C2   C3    C4
0  1.0  4.0  4.0  12.0
1  2.0  5.0  4.0  13.0
2  NaN  NaN  NaN  14.0
3  3.0  3.0  8.0  15.0

# Checking if there are NAs

The question is: Does this `Series` or `DataFrame` contain any missing value? The answer should be yes or no: True or False. How can you verify it?

**Example 1: Checking the length**

If there are missing values, `s.dropna()` will have less elements than ` s`:

In [25]:
s.dropna().count()

np.int64(3)

In [26]:
missing_values = len(s.dropna()) != len(s)
missing_values

True

There's also a `count` method, that excludes `nan`s from its result:

In [27]:
len(s)

5

In [28]:
s.count()

np.int64(3)

So we could just do:

In [29]:
missing_values = s.count() != len(s)
missing_values

np.True_

**More Pythonic solution `any`**

The methods `any `and `all` check if either there's `any` `True` value in a `Series` or `all` the values are `True`. They work in the same way as in Python:

In [30]:
pd.Series([True, False, False]).any()

np.True_

In [31]:
pd.Series([True, False, False]).all()

np.False_

The `isnull()` method returned a Boolean Series with `True` values wherever there was a `nan`:

In [32]:
s.isnull()

0    False
1    False
2     True
3     True
4    False
dtype: bool


So we can just use the `any` method with the boolean array returned:

In [33]:
pd.Series([1, np.nan]).isnull().any()

np.True_

In [34]:
pd.Series([1, 2]).isnull().any()

np.False_

In [35]:
s.isnull().any()

np.True_

A more strict version would check only the values of the `Series`:

In [36]:
s.isnull().values

array([False, False,  True,  True, False])

In [37]:
s.isnull().values.any()

np.True_



---